export const iconsList = [
  {
    name: '🏃‍♂️ Здоровье и спорт',
    icons: [
      { id: 0, name: 'run', url: 'https://www.svgrepo.com/show/431908/run.svg' },
      { id: 1, name: 'walk', url: 'https://www.svgrepo.com/show/432053/walk.svg' },
      { id: 2, name: 'pushups', url: 'https://www.svgrepo.com/show/151991/pushups.svg' },
      { id: 3, name: 'gym', url: 'https://www.svgrepo.com/show/61821/gym-weight.svg' },
      { id: 4, name: 'yoga', url: 'https://www.svgrepo.com/show/355386/yoga.svg' },
      { id: 5, name: 'stretch', url: 'https://www.svgrepo.com/show/159484/stretching.svg' },
      { id: 6, name: 'cycling', url: 'https://www.svgrepo.com/show/490678/cycling.svg' },
      { id: 7, name: 'swimming', url: 'https://www.svgrepo.com/show/521869/swimming.svg' },
      { id: 8, name: 'meditation', url: 'https://www.svgrepo.com/show/321110/meditation.svg' },
      { id: 9, name: 'breathing', url: 'https://www.svgrepo.com/show/389919/lungs.svg' },
      { id: 10, name: 'heart', url: 'https://www.svgrepo.com/show/525944/heart-pulse-2.svg' },
      { id: 11, name: 'heartbeat', url: 'https://www.svgrepo.com/show/528315/heart-pulse.svg' },
      { id: 12, name: 'water', url: 'https://www.svgrepo.com/show/479388/water-drop-4.svg' },
      { id: 13, name: 'sleep', url: 'https://www.svgrepo.com/show/390249/sleep.svg' },
      { id: 14, name: 'alarm', url: 'https://www.svgrepo.com/show/532083/alarm-clock-alt.svg' },
      { id: 15, name: 'sunrise', url: 'https://www.svgrepo.com/show/487854/sunrise.svg' },
    ],
  },
  {
    name: '🧠 Ментальное здоровье',
    icons: [
      { id: 16, name: 'brain', url: 'https://www.svgrepo.com/show/482777/brain-illustration-4.svg' },
      { id: 17, name: 'focus', url: 'https://www.svgrepo.com/show/504353/focus-todo.svg' },
      { id: 18, name: 'no-phone', url: 'https://www.svgrepo.com/show/44621/no-mobile-phone-allowed.svg' },
      { id: 19, name: 'no-smoke', url: 'https://www.svgrepo.com/show/342820/smoke-slash.svg' },
      { id: 20, name: 'journal', url: 'https://www.svgrepo.com/show/344262/journal-bookmark-fill.svg' },
      { id: 21, name: 'mood', url: 'https://www.svgrepo.com/show/368842/mood-tongue.svg' },
      { id: 22, name: 'smile', url: 'https://www.svgrepo.com/show/342732/mood-good.svg' },
      { id: 23, name: 'calm', url: 'https://www.svgrepo.com/show/368836/mood-flat.svg' },
      { id: 24, name: 'lotus', url: 'https://www.svgrepo.com/show/481498/lotus-1.svg' },
      { id: 25, name: 'balance', url: 'https://www.svgrepo.com/show/479891/balance-1.svg' },
      { id: 26, name: 'peace', url: 'https://www.svgrepo.com/show/455978/peace.svg' },
      { id: 27, name: 'self-care', url: 'https://www.svgrepo.com/show/321338/self-love.svg' },
    ],
  },
  {
    name: '📚 Учёба и саморазвитие',
    icons: [
      { id: 28, name: 'book', url: 'https://www.svgrepo.com/show/521518/book-open.svg' },
      { id: 29, name: 'books', url: 'https://www.svgrepo.com/show/385317/books-study-learning-education-reading-library.svg' },
      { id: 30, name: 'reading', url: 'https://www.svgrepo.com/show/309910/reading-mode.svg' },
      { id: 31, name: 'study', url: 'https://www.svgrepo.com/show/308099/study-research-scrutinize-search.svg' },
      { id: 32, name: 'graduation', url: 'https://www.svgrepo.com/show/509972/graduation-cap.svg' },
      { id: 33, name: 'lightbulb', url: 'https://www.svgrepo.com/show/472702/lightbulb-on.svg' },
      { id: 34, name: 'pen', url: 'https://www.svgrepo.com/show/532991/pen-nib.svg' },
      { id: 35, name: 'pencil', url: 'https://www.svgrepo.com/show/532986/pen-clip.svg' },
      { id: 36, name: 'notebook', url: 'https://www.svgrepo.com/show/403894/notebook.svg' },
      { id: 37, name: 'checklist', url: 'https://www.svgrepo.com/show/426074/checklist2.svg' },
      { id: 38, name: 'target', url: 'https://www.svgrepo.com/show/535680/target-arrow.svg' },
      { id: 39, name: 'target2', url: 'https://www.svgrepo.com/show/477511/target-and-arrow.svg' },
      { id: 40, name: 'growth', url: 'https://www.svgrepo.com/show/307505/growth-grow-gardening-plant.svg' },
    ],
  },
  {
    name: '💻 Работа / IT / креатив',
    icons: [
      { id: 41, name: 'code', url: 'https://www.svgrepo.com/show/533324/code.svg' },
      { id: 42, name: 'laptop', url: 'https://www.svgrepo.com/show/528338/laptop-minimalistic.svg' },
      { id: 43, name: 'keyboard', url: 'https://www.svgrepo.com/show/478473/keyboard-2.svg' },
      { id: 44, name: 'mouse', url: 'https://www.svgrepo.com/show/526048/mouse-circle.svg' },
      { id: 45, name: 'terminal', url: 'https://www.svgrepo.com/show/391633/terminal.svg' },
      { id: 46, name: 'bug', url: 'https://www.svgrepo.com/show/524341/bug.svg' },
      { id: 47, name: 'rocket', url: 'https://www.svgrepo.com/show/480798/rocket-11.svg' },
      { id: 48, name: 'design', url: 'https://www.svgrepo.com/show/309513/design-ideas.svg' },
      { id: 49, name: 'palette', url: 'https://www.svgrepo.com/show/480332/palette-8.svg' },
      { id: 50, name: 'figma', url: 'https://www.svgrepo.com/show/473605/figma.svg' },
      { id: 51, name: 'idea', url: 'https://www.svgrepo.com/show/483596/idea-man-person.svg' },
      { id: 52, name: 'brainstorm', url: 'https://www.svgrepo.com/show/204304/brainstorm.svg' },
      { id: 53, name: 'brainstorm2', url: 'https://www.svgrepo.com/show/129449/brainstorm.svg' },
    ],
  },
  {
    name: '🧹 Быт и порядок',
    icons: [
      { id: 54, name: 'clean', url: 'https://www.svgrepo.com/show/339998/clean.svg' },
      { id: 55, name: 'broom', url: 'https://www.svgrepo.com/show/479794/broom-1.svg' },
      { id: 56, name: 'trash', url: 'https://www.svgrepo.com/show/525133/trash-bin-minimalistic.svg' },
      { id: 57, name: 'laundry', url: 'https://www.svgrepo.com/show/489008/laundry.svg' },
      { id: 58, name: 'dish', url: 'https://www.svgrepo.com/show/14839/dish.svg' },
      { id: 59, name: 'home', url: 'https://www.svgrepo.com/show/525383/home-1.svg' },
      { id: 60, name: 'bed', url: 'https://www.svgrepo.com/show/477634/bed-free-2.svg' },
      { id: 61, name: 'plant', url: 'https://www.svgrepo.com/show/428309/plant.svg' },
      { id: 62, name: 'tools', url: 'https://www.svgrepo.com/show/485927/tools.svg' },
      { id: 63, name: 'repair', url: 'https://www.svgrepo.com/show/427589/repair-tool-wrench.svg' },
    ],
  },
  {
    name: '🍎 Питание и привычки тела',
    icons: [
      { id: 64, name: 'apple', url: 'https://www.svgrepo.com/show/481515/apple-6.svg' },
      { id: 65, name: 'banana', url: 'https://www.svgrepo.com/show/450644/banana.svg' },
      { id: 66, name: 'food', url: 'https://www.svgrepo.com/show/482291/food-2.svg' },
      { id: 67, name: 'diet', url: 'https://www.svgrepo.com/show/287250/diet.svg' },
      { id: 68, name: 'no-sugar', url: 'https://www.svgrepo.com/show/443659/food-no-sugar.svg' },
      { id: 69, name: 'coffee', url: 'https://www.svgrepo.com/show/418401/low-mug-drink.svg' },
      { id: 70, name: 'tea', url: 'https://www.svgrepo.com/show/487882/tea-leaf.svg' },
      { id: 71, name: 'water-bottle', url: 'https://www.svgrepo.com/show/297844/water-bottle-bottle.svg' },
      { id: 72, name: 'meal', url: 'https://www.svgrepo.com/show/482038/meal.svg' },
      { id: 73, name: 'kitchen', url: 'https://www.svgrepo.com/show/490139/kitchen-room.svg' },
      { id: 74, name: 'coffee2', url: 'https://www.svgrepo.com/show/493664/coffee-beans-filled-roast-brew.svg' },
    ],
  },
  {
    name: '⏰ Продуктивность и фокус',
    icons: [
      { id: 75, name: 'timer', url: 'https://www.svgrepo.com/show/511175/timer.svg' },
      { id: 76, name: 'pomodoro', url: 'https://www.svgrepo.com/show/532105/clock-lines.svg' },
      { id: 77, name: 'clock', url: 'https://www.svgrepo.com/show/522052/clock.svg' },
      { id: 78, name: 'calendar', url: 'https://www.svgrepo.com/show/529429/calendar.svg' },
      { id: 79, name: 'schedule', url: 'https://www.svgrepo.com/show/525711/calendar.svg' },
      { id: 80, name: 'flag', url: 'https://www.svgrepo.com/show/525340/flag-2.svg' },
      { id: 81, name: 'priority', url: 'https://www.svgrepo.com/show/445991/security-priority.svg' },
      { id: 82, name: 'progress', url: 'https://www.svgrepo.com/show/510146/progress-66.svg' },
      { id: 83, name: 'chart', url: 'https://www.svgrepo.com/show/533351/chart-line-up.svg' },
      { id: 84, name: 'chart2', url: 'https://www.svgrepo.com/show/532410/chart-pie.svg' },
      { id: 85, name: 'stats', url: 'https://www.svgrepo.com/show/532407/chart-mixed.svg' },
    ],
  },
  {
    name: '💰 Финансы',
    icons: [
      { id: 86, name: 'timer', url: 'https://www.svgrepo.com/show/511175/timer.svg' },
      { id: 87, name: 'pomodoro', url: 'https://www.svgrepo.com/show/532105/clock-lines.svg' },
      { id: 88, name: 'clock', url: 'https://www.svgrepo.com/show/522052/clock.svg' },
      { id: 89, name: 'calendar', url: 'https://www.svgrepo.com/show/529429/calendar.svg' },
      { id: 90, name: 'schedule', url: 'https://www.svgrepo.com/show/525711/calendar.svg' },
      { id: 91, name: 'flag', url: 'https://www.svgrepo.com/show/525340/flag-2.svg' },
      { id: 81, name: 'priority', url: 'https://www.svgrepo.com/show/445991/security-priority.svg' },
      { id: 82, name: 'progress', url: 'https://www.svgrepo.com/show/510146/progress-66.svg' },
      { id: 83, name: 'chart', url: 'https://www.svgrepo.com/show/533351/chart-line-up.svg' },
      { id: 84, name: 'chart2', url: 'https://www.svgrepo.com/show/532410/chart-pie.svg' },
      { id: 85, name: 'stats', url: 'https://www.svgrepo.com/show/532407/chart-mixed.svg' },
    ],
  },
]
